### ISSUE TITLE
Add Mutation for Form Submission

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app-api#1]
There is no mutation and table for handing form submissions. Create a mutation `submitForm` to handle form submissions in graphql.

**Comment by Akib-Vijapura** [comment]
I willing to work on this issue.

**Comment by piyushgarg-dev** [comment]
Hey @Akib-Vijapura 
Assigned 😄

**Comment by MrSuperfluous** [comment]
I also want to work on this @piyushgarg-dev

**Comment by Himan-Miku** [comment]
Hey @piyushgarg-dev I also want to work on this issue but as it is already assigned to someone, can you please assign me the next issue? 🥹

**Comment by piyushgarg-dev** [comment]
Hey @Himan-Miku,
You can also work on this issue if you are confident with Graphql 😄

If @Akib-Vijapura Fails to contribute, We'll merge your changes 😄

**Comment by Himan-Miku** [comment]
I'll try my best, thanks @piyushgarg-dev  🙏
