### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by piyushgarg-dev** [piyushgarg-dev/review-app-api#2]
Add a README file in this project to explain what this project is about and various more details about this project to help understand what this project does.

**Comment by Ritish134** [comment]
Hi there excited to contribute, can you please assign me : )

**Comment by sum1t-here** [comment]
Please assign this to me

**Comment by devmusiczz** [comment]
hey @Ritish134 , @piyushgarg-dev has uploaded a video on his channel just now about the overview of this project, you can check that out.

**Comment by piyushgarg-dev** [comment]
Hey @devmusiczz Assigned 😄

**Comment by KunjMaheshwari** [comment]
Hey @piyushgarg-dev Please assign this issue to me.
