### ISSUE TITLE
Add CONTRIBUTING.md file for this repo.

### ISSUE THREAD

**Issue by devmusiczz** [piyushgarg-dev/review-app-api#3]
Hey @piyushgarg-dev, At present there's no contributing.md file present. I have watched your yt video about how someone can set up and contribute to this project. So, I would like to add a contributing.md file for the backend repo of the review app.

**Comment by devmusiczz** [comment]
@piyushgarg-dev Can you please assign this issue to me?

**Comment by piyushgarg-dev** [comment]
Hey @devmusiczz I have assigned a different task to you. Let everyone get a chance here 😉. Would really appreciate if you could guide here to a fellow contributor 😄
Thanks

**Comment by parthksingh1** [comment]
Please assign this issue to me. Thank you!

**Comment by piyushgarg-dev** [comment]
Hey @parthksingh1, Here you go 😄

**Comment by Sanketh149** [comment]
Hey @piyushgarg-dev, Please check my PR. Thank You

**Comment by DeLeNoire** [comment]
I have made my first successful PR thanks to you and your guides ❤️. I hope this helps you, sure did for me.
Expecting more awesome content like this.
In the file added all the steps you went through in your video.
@piyushgarg-dev

**Comment by piyushgarg-dev** [comment]
Closing in ref to https://github.com/piyushgarg-dev/review-app-api/pull/4

**Comment by Sanketh149** [comment]
What merge conflicts does my PR have?
