### ISSUE TITLE
Add deleting a form feature

### ISSUE THREAD

**Issue by SujayShanbhag** [piyushgarg-dev/review-app-api#40]
### Is your proposal related to a problem?

  Right now there is no way to delete forms in the backend.

### Describe the solution you'd like

  A graphQL query that deletes a from.

###Request

 Please let me work on this issue. I've already fixed it locally.

**Comment by surajsingh542** [comment]
@piyushgarg-dev Please assign this issue to me

**Comment by SujayShanbhag** [comment]
@surajsingh542 Hey brother, can you please find another issue. I'm already working on it.

**Comment by surajsingh542** [comment]
@SujayShanbhag Ok no worries.
