### ISSUE TITLE
Updating docker compose command in the README.md file ! 

### ISSUE THREAD

**Issue by saadabban76** [piyushgarg-dev/review-app-api#44]
### Is your proposal related to a problem?

I was stuck for almost 2 hours, trying to figure out why the "docker compose up -d" was not working turns out the command is different for older versions of docker. 

for older version of docker, the command is "docker-compose up -d"
and for the newer version it is "docker up -d"

### Describe the solution you'd like

I would like to update the README.md file, it will be very helpful for the new docker folks like me.

**Comment by MadhurGupta979** [comment]
Hey @saadabban76! Can You Assign Me This Issue ?

**Comment by Divyansh200102** [comment]
please review the pr and merge it @saadabban76

**Comment by saadabban76** [comment]
> please review the pr and merge it @saadabban76

the updates you made in the readme doesn't help this issue, you can find many issues out on review frontend app and be a contributor 😉

**Comment by saadabban76** [comment]
Hi @piyushgarg-dev I have made the changes you can verify and merge the commit 👍🏼
